### PR TITLE
fix: Use `jax.errors` API as `jax._src` removed from public namespace

### LINKED ISSUE #2033: JAX v0.3.18 contains breaking change that fails CI
https://github.com/google/jax/releases/tag/jax-v0.3.18 has a breaking change of

> `jax._src` is no longer imported into the from the public `jax` namespace. This may break users that were using JAX internals.

This breaks the current CI with

```
=================================== FAILURES ===================================
________________________ test_diffable_backend_failure _________________________

    def test_diffable_backend_failure():
        pyhf.set_backend("numpy", default=True)
        pyhf.set_backend("jax")
    
        def example_op(x):
            y = pyhf.default_backend.astensor(x)
            return 2 * y
    
        with pytest.raises(
            (
                ValueError,
>               jax._src.errors.TracerArrayConversionError,
                jax.errors.ConcretizationTypeError,
            )
        ):
E       AttributeError: module 'jax' has no attribute '_src'

example_op = <function test_diffable_backend_failure.<locals>.example_op at 0x7f352304d2d0>

tests/test_backends.py:65: AttributeError
```

as

https://github.com/scikit-hep/pyhf/blob/37abb3b13b75fb161ace06535f3204c423191d18/tests/test_backends.py#L62-L77

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Description

Resolves #2033

This only affects the tests as `jax.errors.TracerArrayConversionError` works in the JAX `v0.2.10` API, so nothing needs to be altered elsewhere.

# Checklist Before Requesting Reviewer

- [x] Tests are passing
- [x] "WIP" removed from the title of the pull request
- [x] Selected an Assignee for the PR to be responsible for the log summary

# Before Merging

For the PR Assignees:

- [x] Summarize commit messages into a comprehensive review of the PR

```
* Use jax.errors API over jax._src.errors as jax._src is removed from the
  jax public namespace in jax v0.3.18.
   - c.f. https://github.com/google/jax/releases/tag/jax-v0.3.18
```

### CODE REVIEW

**Comment by matthewfeickert** [comment]
As this is just updating an API only used in the tests and that passes on the minimum supported dependencies workflow, I'm going to approve and merge this myself. As always, PRs approved by a single core dev can be reverted as needed by the rest of the dev team.
